### ISSUE TITLE
Perl crash when starting openqa-webui, sqlite missing ?

### ISSUE THREAD

**Issue by kkaempf** [os-autoinst/openQA#63]
Following the installation guide, `systemctl start openqa-webui` (as root) fails with the following error

   2014-11-06T14:50:01.445917+01:00 x220 openqa[20035]: Uncaught exception from user code:
   2014-11-06T14:50:01.446211+01:00 x220 openqa[20035]: 
   DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI
   connect('dbname=/var/lib/openqa/db/db.sqlite','',...) failed: unable
   to open database file at
   /usr/lib/perl5/vendor_perl/5.20.1/DBIx/Class/Storage/DBI.pm line 1483.
   at /usr/share/openqa/script/../lib/OpenQA.pm line 123

File `/var/lib/openqa/db/db.sqlite` exists as `-rw-r----- 1 root root 0 Nov  5 14:24 db.sqlite`

**Comment by aaannz** [comment]
I think this can be closed. It is most definitely obsoleted and from what I just noticed, it seems that the problem is that the database is not initialized (file size 0).
So running /usr/share/openqa/script/initdb --init_database (and if file is owned by different user --user=<username>) should fix that
