### ISSUE TITLE
Needles admin page does not show needles in subdirectories

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#786]
We separated the Fedora needles out into subdirectories, with the help of https://github.com/os-autoinst/openQA/pull/613 , but it seems one thing that was missed is the admin interface Needles page, where you can check when needles were last used/matched and delete them; this doesn't seem to be able to find subdirectory-ified needles. On Fedora staging openQA the page shows only two needles, which I think are hangovers from when I initially created those needles in the web UI (our workflow is to create needles in interactive mode - so they show up in the top-level directory - then copy them to our working git checkout, put them in the appropriate subdirectory, commit to git, then delete the original needle from the openQA server and update its git checkout, so the needle shows up in the subdirectory).

@rajcze , since you did the rest of the work...

**Comment by AdamWill** [comment]
@rajcze have you had any time to look at this? looks to me like what's wrong is basically the database's Needles table has no conception of needles being in subdirectories - see https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/Schema/Result/Needles.pm , especially the `path` and `check_file` subroutines. But I don't know immediately how to address this, I figured you'd probably know better since you've already done the rest of the work here.

**Comment by garretraziel** [comment]
We've tried this and we are not really sure, but it looks like it's not caused by #613. When running `openqa-4.3-30.20160708git84c9461.fc24.noarch`, admin UI shows that needle in subdirectory was used (albeit without complete path, we should fix that). When running `openqa-4.4-1.20160826git1ac2387.fc24.noarch`, admin UI doesn't show that needle was used, even when it is placed directly in needle dir.

**Comment by garretraziel** [comment]
OK, I'm doing more testing now and probably there IS a bug in `check_file` when needle is in subdirectory. I'll fix that. OTOH, with openqa-4.4-1.20160826, it didn't work even when needles were directly in needle directory.

**Comment by AdamWill** [comment]
Try with http://koji.fedoraproject.org/koji/taskinfo?taskID=15607367 and http://koji.fedoraproject.org/koji/taskinfo?taskID=15606850 maybe? I just sent 'em to staging yesterday, they seem to be working OK.

**Comment by garretraziel** [comment]
Yeah, I've debugged it yesterday and it is indeed caused by #613. Behavior may be strange when you don't look into the internals (in short - when you create needle outside directory and then move it into directory, its "last used" info gets updated without problem; OTOH when you create needle in directory and then move it outside directory, it won't be shown even then). #868 should fix this, please review whether changed behavior suits you.
